name: pytest
on: workflow_dispatch

jobs:

  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest
